apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: krew-download
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/daniel-garcia/krew-download/releases/download/v0.1.0/krew-download_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./krew-download"
      to: "."
    - from: LICENSE
      to: "."
    bin: "krew-download"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/daniel-garcia/krew-download/releases/download/v0.1.0/krew-download_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./krew-download"
      to: "."
    - from: LICENSE
      to: "."
    bin: "krew-download"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/daniel-garcia/krew-download/releases/download/v0.1.0/krew-download_windows_amd64.zip
    sha256: ""
    files:
    - from: "/krew-download.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "krew-download.exe"
  shortDescription: A new plugin
  homepage: https://github.com/daniel-garcia/krew-download
  caveats: |
    Usage:
      $ kubectl krew-download

    For additional options:
      $ kubectl krew-download --help
      or https://github.com/daniel-garcia/krew-download/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
