name: release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate manifest
        run: |
          make manifest
      - name: Commit manifest
        run: |
          git config user.email "${{ github.event.head_commit.author.email }}"
          git config user.name "${{ github.event.head_commit.author.username || github.event.head_commit.author.name }}"
          git add plugins/krew-download.yaml
          git commit -m "update krew-dowload to $RELEASE_VERSION"
      - name: Push index
        run: |
          git push
      #- name: Update new version in krew-download
      #  uses: rajatjindal/krew-release-bot@v0.0.38
